# Generated by Django 4.2.5 on 2023-10-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_amigo_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigo',
            old_name='nome',
            new_name='Fabricante',
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='nascimento',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='info',
            new_name='informacao',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='amigo',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome'),
        ),
    ]
