# Generated by Django 4.2.5 on 2023-10-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_rename_nome_amigo_fabricante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='informacao',
        ),
        migrations.AddField(
            model_name='amigo',
            name='Assentos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Assentos'),
        ),
        migrations.AddField(
            model_name='amigo',
            name='nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='Fabricante',
            field=models.CharField(max_length=200, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='ano',
            field=models.DateField(blank=True, null=True, verbose_name='Ano de fabricação'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='categoria',
            field=models.CharField(blank=True, max_length=200, verbose_name='Aeronave'),
        ),
        migrations.AlterField(
            model_name='amigo',
            name='modelo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modelo'),
        ),
    ]
