# Generated by Django 4.2.5 on 2023-10-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_remove_amigo_endereco_remove_amigo_informacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigo',
            old_name='Assentos',
            new_name='assentos',
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='Fabricante',
            new_name='fabricante',
        ),
        migrations.AddField(
            model_name='amigo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, verbose_name='whatsapp'),
        ),
    ]
