# Generated by Django 4.2.5 on 2023-10-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0006_rename_assentos_amigo_assentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigo',
            name='assentos',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='categoria',
        ),
    ]
